version: '3.8'

services:
  product-java:
    build:
      context: ./product
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS="-XX:+UseZGC -XX:+ZGenerational"  # Enable Generational ZGC
    networks:
      - product-network

  product-go:
    build:
      context: ./product-go
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - GIN_MODE=dev
    networks:
      - product-network

networks:
  product-network:
    driver: bridge